controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    use_sim_time: True

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: True

gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    use_sim_time: True
